[package]
name = "rss-mdm-native-protection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
rss-data-protection.workspace = true
rss-request-context.workspace = true
ring.workspace = true
zeroize.workspace = true
thiserror.workspace = true
[lints]
workspace = true
