[package]
autotests = false
name = "rss-mdm-apple-mdm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
plist.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
url.workspace = true
thiserror.workspace = true

[lints]
workspace = true
