[package]
name = "rss-mdm-software-release-postgres"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[dependencies]
tracing.workspace = true
rss-mdm-software-release.workspace = true
rss-contract.workspace = true
rss-request-context.workspace = true
rss-transactional-messaging.workspace = true
rss-transactional-messaging-postgres.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
[dev-dependencies]
tokio = {workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util", "sync"]}
[features]
integration = ["rss-transactional-messaging-postgres/integration"]
[lints]
workspace = true

[[test]]
name="recovery"
required-features=["integration"]
