[package]
name = "rss-mdm-resource"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
rss-request-context = { workspace = true }
rss-contract = { workspace = true }
sha2 = { workspace = true }
serde.workspace = true
serde_json.workspace = true
jsonschema.workspace = true
sqlparser = { version = "=0.63.0", default-features = false, features = ["std", "visitor"] }

[lints]
workspace = true
