//! Lower source history to one version-conditioned schema graph, without legacy handlers.
use super::{
    sources::{AppleDocument, AppleSources},
    yaml::Document,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

type Signature = Vec<Option<usize>>;

fn canonical(path: &str) -> String {
    // Official rename in the pinned Release-v27.0 CHANGES.md, not a wire alias.
    path.replace(
        "com.apple.MCX(Mobililty).yaml",
        "com.apple.MCX(Mobility).yaml",
    )
}

pub fn generate(index: &AppleSources, documents: &[AppleDocument]) -> Result<String, String> {
    let lookup = documents
        .iter()
        .map(|d| ((d.path.as_str(), d.digest.as_str()), d))
        .collect::<BTreeMap<_, _>>();
    let mut families: BTreeMap<String, Vec<Option<&AppleDocument>>> = BTreeMap::new();
    for (i, release) in index.releases.iter().enumerate() {
        for (path, object) in &release.files {
            let digest = object.split('.').next().ok_or("source digest")?;
            if let Some(&document) = lookup.get(&(path.as_str(), digest)) {
                families
                    .entry(canonical(path))
                    .or_insert_with(|| vec![None; index.releases.len()])[i] = Some(document);
            }
        }
    }
    let mut out = String::from(
        "// Generated by the rss-mdm-native-schema. Do not edit.\nuse super::{Atom, Field, FieldRule, Definition, Kind, Source, Conditions, Availability, Variant};\n",
    );
    let mut definitions = Vec::new();
    for (path, states) in families {
        let mut available = Vec::new();
        let mut native_identity = None;
        let (kind, identity_key) = if path.starts_with("mdm/commands/") {
            ("Command", "requesttype")
        } else if path.starts_with("mdm/checkin/") {
            ("Checkin", "requesttype")
        } else if path.starts_with("mdm/profiles/") {
            ("Profile", "payloadtype")
        } else if path.starts_with("mdm/errors/") {
            ("Error", "errorchain")
        } else if path.starts_with("declarative/declarations/assets/credentials/") {
            ("Credential", "credentialtype")
        } else if path.starts_with("declarative/declarations/") {
            ("Declaration", "declarationtype")
        } else if path.starts_with("declarative/status/") {
            ("Status", "statusitemtype")
        } else {
            ("Protocol", "requesttype")
        };
        for document in &states {
            let Some(document) = document else {
                available.push(None);
                continue;
            };
            let d = &document.source;
            let payload = d.get(d.root(), "payload").ok_or("schema lacks payload")?;
            let mac = d
                .get(payload, "supportedOS")
                .and_then(|p| d.get(p, "macOS"));
            let Some(mac) = mac else {
                if document.path == "mdm/profiles/com.apple.security.wapi-identity.yaml"
                    && document.digest
                        == "d1ea24f20cb1055b7801da2a8de08e2b1959db27b96902a1056f788eb0ad7ffd"
                {
                    available.push(None);
                    continue;
                }
                return Err(format!(
                    "{} has no declared macOS applicability",
                    document.path
                ));
            };
            if d.optional_text(mac, "introduced")? == Some("n/a") {
                available.push(None);
                continue;
            }
            if d.optional_text(payload, "beta")? == Some("true")
                || d.optional_text(mac, "beta")? == Some("true")
            {
                available.push(None);
                continue;
            }
            let identity = d.optional_text(payload, identity_key)?.unwrap_or(&path);
            if native_identity
                .as_deref()
                .is_some_and(|old| old != identity)
            {
                return Err(format!("native identity changed: {path}"));
            }
            native_identity = Some(identity.to_owned());
            let condition = conditions(d, mac)?;
            available.push(Some(format!(
                "Availability{{conditions:{condition},source:Source{{path:{:?},sha256:{:?}}}}}",
                document.path, document.digest
            )));
        }
        let Some(identity) = native_identity else {
            continue;
        };
        let eligible_states = states
            .iter()
            .zip(&available)
            .map(|(state, support)| if support.is_some() { *state } else { None })
            .collect::<Vec<_>>();
        let mut fields = Fields {
            states: &eligible_states,
            ids: BTreeMap::new(),
            ordered: Vec::new(),
        };
        let request = fields.list(roots(&eligible_states, "payloadkeys"))?;
        let response = fields.list(roots(&eligible_states, "responsekeys"))?;
        let prefix = format!("D{}", definitions.len());
        let mut emitted = Vec::new();
        let mut next = 0;
        while next < fields.ordered.len() {
            let signature = fields.ordered[next].clone();
            emitted.push(fields.emit(&signature, index)?);
            next += 1;
        }
        writeln!(
            &mut out,
            "static {prefix}_FIELDS: &[Field] = &[{}];",
            emitted.join(",\n")
        )
        .map_err(|e| e.to_string())?;
        definitions.push(format!("Definition{{kind:Kind::{kind},identity:{identity:?},schema:{path:?},availability:&{},fields:{prefix}_FIELDS,request:&{request:?},response:&{response:?}}}",variants(&available,index)?));
    }
    out.push_str("// Historical WAPI source d1ea24f20cb1055b7801da2a8de08e2b1959db27b96902a1056f788eb0ad7ffd has no declared macOS applicability and is not executable.\n");
    writeln!(
        &mut out,
        "pub(super) static DEFINITIONS: &[Definition] = &[{}];",
        definitions.join(",\n")
    )
    .map_err(|e| e.to_string())?;
    Ok(out)
}

fn roots(states: &[Option<&AppleDocument>], key: &str) -> Signature {
    states
        .iter()
        .map(|s| s.and_then(|s| s.source.get(s.source.root(), key)))
        .collect()
}

pub(crate) fn version(s: &str) -> Result<[u32; 3], String> {
    let parts = s
        .split('.')
        .map(str::parse::<u32>)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;
    if parts.is_empty() || parts.len() > 3 {
        return Err("invalid release version".into());
    }
    let mut result = [0; 3];
    result[..parts.len()].copy_from_slice(&parts);
    Ok(result)
}

fn variants(values: &[Option<String>], index: &AppleSources) -> Result<String, String> {
    // The newest official definition describes OS applicability. Publication time
    // is provenance, never a lower OS bound for a newly documented field.
    let Some(last) = values.iter().rposition(Option::is_some) else {
        return Ok("[]".into());
    };
    let before = index
        .releases
        .get(last + 1)
        .map(|release| version(&release.release))
        .transpose()?;
    let value = values[last]
        .as_ref()
        .ok_or("missing latest schema definition")?;
    Ok(format!(
        "[Variant{{from:[0,0,0],before:{before:?},value:{value}}}]"
    ))
}

struct Fields<'a> {
    states: &'a [Option<&'a AppleDocument>],
    ids: BTreeMap<Signature, usize>,
    ordered: Vec<Signature>,
}
impl Fields<'_> {
    fn list(&mut self, sequences: Signature) -> Result<Vec<usize>, String> {
        let mut keys: BTreeMap<String, Signature> = BTreeMap::new();
        for (i, sequence) in sequences.into_iter().enumerate() {
            let Some(sequence) = sequence else { continue };
            let d = &self.states[i].ok_or("field has no source")?.source;
            for &node in d.sequence(sequence)? {
                let key = d.optional_text(node, "key")?.ok_or("field has no key")?;
                let signature = keys
                    .entry(key.into())
                    .or_insert_with(|| vec![None; self.states.len()]);
                if signature[i].replace(node).is_some() {
                    return Err(format!("duplicate schema field {key}"));
                }
            }
        }
        let mut result = Vec::new();
        for signature in keys.into_values() {
            let next = self.ids.len();
            let id = *self.ids.entry(signature.clone()).or_insert_with(|| {
                self.ordered.push(signature);
                next
            });
            result.push(id);
        }
        Ok(result)
    }
    fn emit(&mut self, signature: &Signature, index: &AppleSources) -> Result<String, String> {
        let children = signature
            .iter()
            .enumerate()
            .map(|(i, id)| {
                id.and_then(|id| self.states[i].and_then(|s| s.source.get(id, "subkeys")))
            })
            .collect();
        let children = self.list(children)?;
        let mut values = Vec::new();
        let mut name = None;
        for (i, node) in signature.iter().enumerate() {
            let Some(node) = node else {
                values.push(None);
                continue;
            };
            let d = &self.states[i].ok_or("field source absent")?.source;
            name = Some(d.optional_text(*node, "key")?.ok_or("field key")?);
            values.push(Some(rule(d, *node, &children)?));
        }
        Ok(format!(
            "Field{{key:{:?},wildcard:{},variants:&{}}}",
            name.ok_or("empty field")?,
            name.is_some_and(|n| n == "ANY" || n.starts_with("ANY ")),
            variants(&values, index)?
        ))
    }
}

fn rule(d: &Document, id: usize, children: &[usize]) -> Result<String, String> {
    let atom = match d
        .optional_text(id, "type")?
        .ok_or("schema type is missing")?
    {
        "<string>" => "String",
        "<integer>" => "Integer",
        "<real>" => "Real",
        "<boolean>" => "Boolean",
        "<date>" => "Date",
        "<data>" => "Data",
        "<array>" => "Array",
        "<dictionary>" => "Dictionary",
        "<any>" => "Any",
        unknown => return Err(format!("unsupported official type {unknown}")),
    };
    let required = match d.optional_text(id, "presence")? {
        Some("required") => true,
        Some("optional") | None => false,
        Some(s) => return Err(format!("unknown presence {s}")),
    };
    let condition = d
        .get(id, "supportedOS")
        .and_then(|n| d.get(n, "macOS"))
        .map(|n| conditions(d, n))
        .transpose()?
        .unwrap_or_else(|| "Conditions::INHERIT".into());
    let ranges = strings(d, d.get(id, "rangelist"))?;
    let bounds = d.get(id, "range");
    let min = bounds
        .map(|n| d.optional_text(n, "min"))
        .transpose()?
        .flatten();
    let max = bounds
        .map(|n| d.optional_text(n, "max"))
        .transpose()?
        .flatten();
    let format = d.optional_text(id, "format")?;
    let value_type = d
        .optional_text(id, "valuetype")?
        .or(d.optional_text(id, "subtype")?);
    let count = d.get(id, "repetition");
    let min_items = count
        .map(|n| d.optional_text(n, "min"))
        .transpose()?
        .flatten();
    let max_items = count
        .map(|n| d.optional_text(n, "max"))
        .transpose()?
        .flatten();
    let asset_types = strings(d, d.get(id, "assettypes"))?;
    let asset_content_types = strings(d, d.get(id, "asset-content-types"))?;
    Ok(format!(
        "FieldRule{{atom:Atom::{atom},required:{required},conditions:{condition},children:&{children:?},range:&{ranges:?},min:{min:?},max:{max:?},format:{format:?},value_type:{value_type:?},min_items:{min_items:?},max_items:{max_items:?},asset_types:&{asset_types:?},asset_content_types:&{asset_content_types:?}}}"
    ))
}

fn strings(d: &Document, sequence: Option<usize>) -> Result<Vec<&str>, String> {
    sequence
        .map(|s| d.sequence(s)?.iter().map(|&v| d.text(v)).collect())
        .unwrap_or(Ok(Vec::new()))
}

fn conditions(d: &Document, id: usize) -> Result<String, String> {
    let known: BTreeSet<_> = [
        "introduced",
        "deprecated",
        "removed",
        "beta",
        "devicechannel",
        "userchannel",
        "supervised",
        "requiresdep",
        "userapprovedmdm",
        "userenrollment",
        "allowed-enrollments",
        "allowed-scopes",
        "accessrights",
        "multiple",
        "allowmanualinstall",
        "sharedipad",
    ]
    .into_iter()
    .collect();
    let extra = d
        .mapping(id)?
        .keys()
        .filter(|k| !known.contains(k.as_str()))
        .collect::<Vec<_>>();
    if !extra.is_empty() {
        return Err(format!("unclassified macOS applicability: {extra:?}"));
    }
    let mut fields = Vec::new();
    for (key, name) in [
        ("introduced", "introduced"),
        ("removed", "removed"),
        ("accessrights", "access_rights"),
    ] {
        fields.push(format!("{name}:{:?}", d.optional_text(id, key)?));
    }
    for (key, name) in [
        ("beta", "beta"),
        ("devicechannel", "device_channel"),
        ("userchannel", "user_channel"),
        ("supervised", "supervised"),
        ("requiresdep", "automated_enrollment"),
        ("userapprovedmdm", "user_approved"),
        ("multiple", "multiple"),
    ] {
        let v = match d.optional_text(id, key)? {
            Some("true") => Some(true),
            Some("false") => Some(false),
            None => None,
            _ => return Err(format!("non-boolean condition {key}")),
        };
        fields.push(format!("{name}:{v:?}"));
    }
    let enrollment = d
        .get(id, "userenrollment")
        .map(|n| d.optional_text(n, "mode"))
        .transpose()?
        .flatten();
    fields.push(format!("user_enrollment:{enrollment:?}"));
    fields.push(format!(
        "enrollments:&{:?}",
        strings(d, d.get(id, "allowed-enrollments"))?
    ));
    fields.push(format!(
        "scopes:&{:?}",
        strings(d, d.get(id, "allowed-scopes"))?
    ));
    Ok(format!("Conditions{{{}}}", fields.join(",")))
}
